name: LaFleur
favicon: null
layout_spectrum: 0.46524183452129364
typography_spectrum: 0.5011881722602993
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.09915555780753493
  lightness: 0.9371341171208769
  saturation: 0.27337594400160015
  rhythmicContrast: 0.3906115044374019
purpose: []
